Roopchansinghv/osx 64 builds
gadgetron/gadgetron-conda-recipes pull request #17
Opened 2022-02-16 14:18 UTC by roopchansinghv

Trying again to build, but this time, using Conda's environment setup documentation [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#macos-and-linux) and [here](https://conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#using-the-compiler-packages), to specify C and C++ compilers in environment to make and cmake.

2022-02-16 23:23 UTC, hansenms requested changes
We should add a git workflow, which builds on macos. If we are unable to get the gadgetron building for now, we can just get the dependencies in by explicitly listing the packages we want to build, e.g.:

```bash
./build.sh -p ismrmrd -p ismrmrd-pyton -p ...
```

So we get the ones we have working built and pushed.

2022-02-16 23:23 UTC, hansenms commented on siemens_to_ismrmrd/meta.yaml
> +  home:
Let's try to add meta data when we update these packages.

2022-02-16 23:23 UTC, hansenms commented on gadgetron-python/meta.yaml
> +  home:
Let's try to add metadata when we touch up these packages.

2022-02-18 13:46 UTC, roopchansinghv commented
Okay - closing this PR, and opening another with auto-building support packages on macOS.

2022-02-18 13:46 UTC, closed without merging